services:
  auth:
    build:
      context: ./apps/auth
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/auth:/app

  game:
    build:
      context: ./apps/game
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/game:/app

  front:
    volumes:
      - ./apps/front:/app
      - /app/node_modules
